language: c

sudo: true

#Cache devkitARM and doxygen
cache:
  directories:
    - /home/travis/devkitPro

before_install:
  - wget https://github.com/devkitPro/pacman/releases/download/v1.0.0/devkitpro-pacman.deb
  - sudo dpkg -i devkitpro-pacman.deb

install:
  - sudo dkp-pacman -Syu switch-dev --noconfirm --needed
  - sudo dkp-pacman -S switch-libpng --noconfirm
  - sudo dkp-pacman -S switch-libjpeg-turbo --noconfirm
  - sudo dkp-pacman -S switch-sdl2 --noconfirm
  - sudo dkp-pacman -S switch-sdl2_gfx --noconfirm
  - sudo dkp-pacman -S switch-sdl2_image --noconfirm
  - sudo dkp-pacman -S switch-sdl2_ttf --noconfirm
  - source /etc/profile.d/devkit-env.sh
  - sh resources/.travis-deps.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - sh resources/.build.sh
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: travis-fix